#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FG_App.Resource", IsApplication=true)]

namespace FG_App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonSignUpStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int EditTextStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int IcNavigationDrawer = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Main = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int monoandroidsplash = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int slider_hdr2s = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int container = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int diesv = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int fragment_container = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int horizontalScrollView1 = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int imageUnsereSchule = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int imageView1 = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public const int imageView2 = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int leftListView = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int myDrawer = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int postListView = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int postTitle = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int scrollView1 = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Aktuelles = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Einstellungen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Klausuren = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Kontakt = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RSSItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Schule = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SV = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Termine = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int close_drawer = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int open_drawer = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int CustomActionBarTheme = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int MyActionBar = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
